<?php

/**
 * Implements hook_wm_item().
 */
function wm_contents_wm_item() {
  $images = drupal_get_path('module', 'wm_contents') . '/images/';

  $items['content'] = array(
      '#title' => 'Content',
      '#class' => array(),
      '#weigth' => 0,
      '#items' => array('contents' => array(
            'icon' => $images . 'documents.png',
            'title' => t('Contents'),
            'href' => 'admin/content',
            'help' => t('View all contents'),
            'shortcut' => TRUE,
          //'notification_callback' => '',
        ), ),
  );

  $items['content']['#items'] = array_merge($items['content']['#items'], _wm_contents_get_content());

  return $items;
}

function _wm_contents_get_content() {
  $images = drupal_get_path('module', 'wm_contents') . '/images/';
  $types = node_type_get_types();

  $contents = array();
  foreach ($types as $key => $type) {
    if (node_access('create', $type -> type)) {
      $contents['create-' . $key] = array(
          'icon' => $images . 'document--plus.png',
          'title' => t('Create a new !type', array('!type' => $type -> name)),
          'href' => 'node/add/' . strtr($type -> type, '_', '-'),
          'help' => t('Create a new !type', array('!type' => $type -> name)),
          'shortcut' => TRUE,
      );
    }
  }

  return $contents;
}
