<?php

/**
 * Implements hook_wm_item().
 */
function wm_admin_wm_item() {

  $items = array();

  if (user_access('access full admin')) {

    $images = drupal_get_path('module', 'wm_admin') . '/images/';

    $items['admin'] = array(
        '#title' => 'Admin',
        '#class' => array(),
        '#weigth' => 1,
        '#items' => array(
            'structure' => array(
                'icon' => $images . 'sitemap.png',
                'title' => t('Structure'),
                'href' => 'admin/structure',
                'help' => t('Administer blocks, content types, menus, etc.'),
                'shortcut' => TRUE,
            ),
            'appearance' => array(
                'icon' => $images . 'layout-header-3-mix.png',
                'title' => t('Appearance'),
                'href' => 'admin/appearance',
                'help' => t('Select and configure your themes.'),
            ),
            'modules' => array(
                'icon' => $images . 'puzzle.png',
                'title' => t('Modules'),
                'href' => 'admin/modules',
                'help' => t('Extend site functionality.'),
            ),
            'people' => array(
                'icon' => $images . 'users.png',
                'title' => t('People'),
                'href' => 'admin/people',
                'help' => t('Manage user accounts, roles, and permissions.'),
            ),
            'config' => array(
                'icon' => $images . 'gear.png',
                'title' => t('Config'),
                'href' => 'admin/config',
                'help' => t('Administer settings.'),
            ),
            'reports' => array(
                'icon' => $images . 'reports.png',
                'title' => t('Reports'),
                'href' => 'admin/reports',
                'help' => t('View reports, updates, and errors.'),
            ),
        ),
    );

  }

  return $items;
}

/**
 * Implements hook_permission().
 */
function wm_admin_permission() {
  return array('access full admin' => array(
        'title' => t('Access full admin'),
        'description' => t('Access full admin.'),
    ));
}
